/**
 * The agent roster.
 *
 * Static fields (name / strategy / port) live here. The per-agent Sui address,
 * secret key, and public endpoint are generated by `scripts/setup-agents.ts`
 * and stored in `.agents.json` (gitignored). `loadRoster()` merges the two.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface AgentDef {
  name:     string;
  strategy: string;
  port:     number;
}

export interface AgentSecret {
  name:      string;
  address:   string;
  secretKey: string; // bech32 suiprivkey1... (from keypair.getSecretKey())
  endpoint:  string; // public URL registered on-chain, e.g. https://x.trycloudflare.com/predict
}

/** The canonical roster. Edit ports here if they collide with other services. */
export const ROSTER: AgentDef[] = [
  { name: 'imbalance', strategy: 'imbalance', port: 3002 },
  { name: 'momentum',  strategy: 'momentum',  port: 3003 },
  { name: 'reversion', strategy: 'reversion', port: 3004 },
  { name: 'wide',      strategy: 'wide',      port: 3005 },
];

export const SECRETS_PATH = path.join(__dirname, '..', '.agents.json');

export function loadSecrets(): AgentSecret[] {
  if (!fs.existsSync(SECRETS_PATH)) return [];
  return JSON.parse(fs.readFileSync(SECRETS_PATH, 'utf8')) as AgentSecret[];
}

export function saveSecrets(secrets: AgentSecret[]): void {
  fs.writeFileSync(SECRETS_PATH, JSON.stringify(secrets, null, 2) + '\n');
}

export interface ResolvedAgent extends AgentDef {
  address:  string;
  endpoint: string;
}

/** Merge static roster with generated addresses. Throws if keys are missing. */
export function loadRoster(): ResolvedAgent[] {
  const secrets = loadSecrets();
  return ROSTER.map((def) => {
    const s = secrets.find((x) => x.name === def.name);
    if (!s) {
      throw new Error(
        `No key for "${def.name}". Run \`npm run setup -- gen\` first to generate agent keypairs.`,
      );
    }
    return { ...def, address: s.address, endpoint: s.endpoint };
  });
}
